[clients]
node11-4.grid.orbit-lab.org ansible_host=10.20.11.4
node11-7.grid.orbit-lab.org ansible_host=10.20.11.7
node11-10.grid.orbit-lab.org ansible_host=10.20.11.10
node11-14.grid.orbit-lab.org ansible_host=10.20.11.14
node11-17.grid.orbit-lab.org ansible_host=10.20.11.17
node11-19.grid.orbit-lab.org ansible_host=10.20.11.19
node11-20.grid.orbit-lab.org ansible_host=10.20.11.20

[clients:vars]
ansible_user=root
