# -*- coding: utf-8 -*-
"""DLhw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W5b-CEhRPMShv4OiIwwC_BckMXcU8kFn
"""

import torch
import math
x1 = torch.tensor([1.],requires_grad=True)
x2 = torch.tensor([math.pi/3],requires_grad=True)
w1 = torch.tensor([3.],requires_grad=True)
w2 = torch.tensor([1.],requires_grad=True)

f1 = x1*w1
f2 = x2*w2
f3 = torch.sin(f1)
f4 = torch.cos(f2)
f5 = f3**2
f6 = f4+f5+2
f = 1/f6
f.backward()
print(x1.grad, x2.grad, w1.grad, w2.grad)